import random
#1
# list1 = [1, 2, 3, 4, 5, 6]
# print(random.choice(list1))
# string = "striver"
# print(random.choice(string))

#2
#seed():- Seed function is used to save the state of a random function so that it can generate some random numbers on multiple executions of the code on the same machine or on different machines (for a specific seed value). The seed value is the previous value number generated by the generator. For the first time when there is no previous value, it uses current system time.

# print(random.random())
# random.seed(7)
# print("The mapped random number with 5 is : ", end="")
# print(random.random())

#3
sample_list = ['A', 'B', 'C', 'D', 'E']
random.shuffle(sample_list)
print(sample_list)


#4
# uniform(a, b):- This function is used to generate a floating point random number between the numbers mentioned in its arguments. It takes two arguments, lower limit(included in generation) and upper limit(not included in generation).

print("The random floating point number between 5 and 10 is : ", end="")
print(random.uniform(5, 10))

#5
# random.randint(1,10)
# random.randrange(stop)
# random.randrange(1,10,2)





